import marshal
import dis
import io
from contextlib import redirect_stdout

# Path to the compiled bytecode file (generated by py_compile)
pyc_file = r"C:\Users\jaswa\Challenge5\Differential_Equation\__pycache__\differential_eqution.cpython-312.pyc"

# Read the .pyc file and load the code object.
with open(pyc_file, "rb") as f:
    header_size = 16  # Adjust this if your Python version uses a different header size.
    f.read(header_size)  # Skip the header
    code_obj = marshal.load(f)

# Prepare the output file for the disassembled instructions.
output_file = "bytecode_disassembly.txt"
with open(output_file, "w") as f_out:
    # Redirect stdout to capture the output of dis.dis()
    with redirect_stdout(f_out):
        dis.dis(code_obj)

print(f"Bytecode disassembly written to {output_file}")